-- State-agency rule codify: Olympic National Forest Pet Policy - 36 CFR §261.50 + forest admin (on-leash in developed areas; under control in backcountry)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Forest Service (id=292)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=USFS unit_name~'%olympic national forest%'
-- Affected beaches: 2
--
--   fid 9794  Little Ireland Beach
--   fid 16374628  Seal Rock Camground
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'Olympic National Forest Pet Policy - 36 CFR §261.50 + forest admin (on-leash in developed areas; under control in backcountry)',
       292,
       ARRAY['dog_policy']::text[],
       'https://www.fs.usda.gov/r06/olympic/wilderness',
       'Olympic National Forest — Pet Policy

OPERATIVE RULE (36 CFR §261.50 + Olympic NF admin policy):
- General Areas: Pets must be under control or on a leash
- Developed Recreation Areas (trailheads, campgrounds, busy trails): Pets must be leashed (no longer than 6 feet) and under control
- Wilderness Areas: Pets are welcome as long as they are kept on a leash or under control and quiet
- Pet Waste: Must be properly buried or packed out
- National Park Boundary: Pets NOT permitted in adjacent Olympic NP

Citation: Olympic National Forest Pet Policy + 36 CFR §261.50(a)(b)
URL: https://www.fs.usda.gov/r06/olympic/wilderness
Verbatim: "Pets are welcome in Olympic National Forest Wilderness as long as they are kept on a leash or under control, and quiet."
Subtype: agency_administrative_policy (forest-level enforcement of 36 CFR §261.50)

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'agent_dispatch_2026_05_18_afk')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.fs.usda.gov/r06/olympic/wilderness'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'on leash or under control',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9794::bigint)  /* Little Ireland Beach */,
             (16374628::bigint)  /* Seal Rock Camground */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.fs.usda.gov/r06/olympic/wilderness'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
