-- State-agency rule codify: Oregon Islands NWR Wilderness Area — 50 CFR §26.21 (Pets/Domestic Animals; refuge-wide prohibition)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-19
--
-- Agency: United States Fish and Wildlife Service (id=308)
-- Subtype: federal_regulation
-- Rule:    not_allowed  (section=sand)
-- States:  OR
-- PAD-US filter: mng_type=FED mng_name=FWS des_tp=WA unit_name~'%Oregon Islands%'
-- Affected beaches: 12
--
--   fid 9777  Baker Beach
--   fid 17326257  D River Beach Wayside
--   fid 8314398  D River State Recreation Area
--   fid 9741  Merchants Beach
--   fid 9786  Moolack Beach
--   fid 9763  Neskowin Beach
--   fid 1439671  Ocean Beach
--   fid 9790  Short Sand Beach
--   fid 9773  Sporthaven Beach
--   fid 9715  Tolovana Beach SRS
--   fid 1764302  Tunnel Beach
--   fid 9739  Wakeman Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'Oregon Islands NWR Wilderness Area — 50 CFR §26.21 (Pets/Domestic Animals; refuge-wide prohibition)',
       308,
       ARRAY['dog_policy']::text[],
       'https://www.ecfr.gov/current/title-50/chapter-I/subchapter-C/part-26/subpart-B/section-26.21',
       'USFWS Oregon Islands National Wildlife Refuge — Pets / Domestic Animals Policy
================================================================================

SCOPE OF THIS RECORD
This record codifies the operative pets rule for the Oregon Islands National
Wildlife Refuge WILDERNESS AREA subset (12 PAD-US units, des_tp=WA). For the
mainland Coquille Point subset (des_tp=NWR; on-leash permitted) see existing
policy_source row id=275.

================================================================================
PRIMARY OPERATIVE TEXT — 50 CFR §26.21 (General trespass provision)
Source: https://www.ecfr.gov/current/title-50/chapter-I/subchapter-C/part-26/subpart-B/section-26.21
Mirror: https://www.law.cornell.edu/cfr/text/50/26.21
================================================================================

(a) No person shall trespass, including but not limited to entering, occupying,
using, or being upon, any national wildlife refuge, except as specifically
authorized in this subchapter C or in other applicable Federal regulations.

(b) No unconfined domestic animals, including but not limited to dogs, hogs,
cats, horses, sheep and cattle, shall be permitted to enter upon any national
wildlife refuge or to roam at large upon such an area, except as specifically
authorized under the provisions of § 26.34, § 27.91 or § 29.2 of this
subchapter C.

================================================================================
REFUGE-SPECIFIC CLOSURE — Oregon Islands NWR Rules & Policies
Source: https://www.fws.gov/refuge/oregon-islands/visit-us/rules-policies
================================================================================

"There is no public access to the rocks, reefs and islands of this refuge at
any time."

"These National Wildlife Refuges are maintained for the protection of
wildlife... These areas enjoy the most stringent restrictions of all federal
lands in the U.S., managed to preserve Wilderness characteristics."

"All migratory birds are protected under the Migratory Bird Treaty Act ... and
all Marine Mammals are protected under the Marine Mammal Protection Act
(MMPA). These Acts forbid the harassment of these animals."

================================================================================
WILDERNESS LAYER — Oregon Islands Wilderness (P.L. 91-504, 1970)
================================================================================

The Oregon Islands Wilderness was designated by Public Law 91-504 (Oct 23,
1970) and expanded in 1978 and 1996. Wilderness Act §4(c) (16 U.S.C. §1133(c))
prohibits commercial enterprise, motorized equipment, and other intrusive
uses; domestic animal access is also constrained by the underlying NWR closure.

================================================================================
DOG WALKING ACTIVITY PAGE (for cross-reference; covers Coquille Point only)
Source: https://www.fws.gov/refuge/oregon-islands/visit-us/activities/dog-walking
================================================================================

"Dogs are permitted only at Coquille Point."

"For the protection of pets, wildlife and visitors, all pets are required to
be on leash."

================================================================================
APPLICATION TO THE 12 WILDERNESS-AREA BEACHES
================================================================================

Per PAD-US (des_tp=WA, unit_name=''Oregon Islands National Wildlife Refuge
Wilderness Area''), the following 12 beaches intersect the closed wilderness
subset and are therefore subject to:
  (1) the refuge-wide "no public access" closure stated on the rules-and-
      policies page;
  (2) 50 CFR §26.21 prohibition on unconfined domestic animals on any NWR
      (no §26.34 / §27.91 / §29.2 carve-out has been published for these
      units).

Operative rule for pets/dogs on these 12 units: NOT ALLOWED.

Beach fids (from beach_relevant_pad_us × beaches_gold spatial join):
  9715 Tolovana Beach SRS
  9739 Wakeman Beach
  9741 Merchants Beach
  9763 Neskowin Beach
  9773 Sporthaven Beach
  9777 Baker Beach
  9786 Moolack Beach
  9790 Short Sand Beach
  1439671 Ocean Beach
  1764302 Tunnel Beach
  8314398 D River State Recreation Area
  17326257 D River Beach Wayside

NOTE on PAD-US imprecision: the Wilderness Area polygon technically covers the
offshore rocks/islands; several of these beaches are MAINLAND beaches (state
parks / waysides) that share an intersecting PAD-US polygon due to coastline
geometry. The pets-prohibition statement is operative for the Wilderness Area
fraction of each unit; the mainland fraction inherits its rule from the
overlying state-park/wayside authority (OPRD OAR 736-010-0030, already
codified). Consensus engine layers both.

[Sources fetched via WebSearch/WebFetch 2026-05-19.]

[Codified via codify v1 --state-agency-rule 2026-05-19.]',
       NULL::date,
       NOW(),
       NULL
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.ecfr.gov/current/title-50/chapter-I/subchapter-C/part-26/subpart-B/section-26.21'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'not_allowed',
       'operative'::operative_status,
       '50 CFR §26.21(b): ''No unconfined domestic animals, including but not limited to dogs ... shall be permitted to enter upon any national wildlife refuge or to roam at large upon such an area.'' Refuge: ''There is no public access to the rocks, reefs and islands of this refuge at any time.''',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9777::bigint)  /* Baker Beach */,
             (17326257::bigint)  /* D River Beach Wayside */,
             (8314398::bigint)  /* D River State Recreation Area */,
             (9741::bigint)  /* Merchants Beach */,
             (9786::bigint)  /* Moolack Beach */,
             (9763::bigint)  /* Neskowin Beach */,
             (1439671::bigint)  /* Ocean Beach */,
             (9790::bigint)  /* Short Sand Beach */,
             (9773::bigint)  /* Sporthaven Beach */,
             (9715::bigint)  /* Tolovana Beach SRS */,
             (1764302::bigint)  /* Tunnel Beach */,
             (9739::bigint)  /* Wakeman Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.ecfr.gov/current/title-50/chapter-I/subchapter-C/part-26/subpart-B/section-26.21'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
