-- State-agency rule codify: Columbia River Gorge NSA Pet Policy - 36 CFR §261.16(j) (developed areas)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Forest Service (id=292)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  OR,WA
-- PAD-US filter: mng_type=FED mng_name=USFS unit_name~'%columbia river gorge%'
-- Affected beaches: 8
--
--   fid 9831  Home Valley Beach
--   fid 9757  Koberg Beach
--   fid 6947591  Luhr Jensen Beach
--   fid 9784  Marina Beach
--   fid 9761  Rock Creek Beach
--   fid 9745  Sandy River Beach
--   fid 9779  Slackwater Beach
--   fid 9797  Windboarding Beachhead
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'Columbia River Gorge NSA Pet Policy - 36 CFR §261.16(j) (developed areas)',
       292,
       ARRAY['dog_policy']::text[],
       'https://www.fs.usda.gov/r06/columbiarivergorge/',
       'Columbia River Gorge National Scenic Area (USFS — OR + WA Columbia River Gorge) — Pet Policy

OPERATIVE RULE (36 CFR §261.16(j) baseline + site-specific designations):
- Developed recreation sites: Dogs MUST be on a leash no longer than 6 feet
- Most hiking trails throughout CRGNSA require dogs to be "on a leash and/or under voice command"
- Voice control is NOT formally documented as an NSA-wide alternative; on-leash is the default

Site-specific examples:
- Eagle Creek Trail: All dogs must be on leash (cliff hazards)
- Coyote Wall Trailhead: Dogs must be on leash December 1 – June 30 (seasonal wildlife protection)
- Sandy River Delta: On-leash in parking lot, bathroom, picnic areas, and within 100 ft of Confluence Trail; off-leash permitted beyond 100 ft in non-sensitive areas
- Catherine Creek: Dogs on leash in Catherine Creek planning area year round
- Multnomah Falls: Keep pets on leash in parking, plaza, paved trail portions

Citation: Columbia River Gorge NSA Pet Policy + 36 CFR §261.16(j) (developed recreation pet requirements)
URL: https://www.fs.usda.gov/r06/columbiarivergorge/
Verbatim: "Bringing in or possessing an animal, other than a service animal, unless it is crated, caged, or upon a leash not longer than six feet, or otherwise under physical restrictive control." (36 CFR §261.16(j))

Subtype: federal_regulation (36 CFR baseline; site-specific variations exist for Sandy River Delta off-leash carve-out + Coyote Wall seasonal). Per-site refinement deferred to curator review.

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'agent_dispatch_2026_05_18_afk')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.fs.usda.gov/r06/columbiarivergorge/'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       '6-ft leash baseline; site-specific variations',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9831::bigint)  /* Home Valley Beach */,
             (9757::bigint)  /* Koberg Beach */,
             (6947591::bigint)  /* Luhr Jensen Beach */,
             (9784::bigint)  /* Marina Beach */,
             (9761::bigint)  /* Rock Creek Beach */,
             (9745::bigint)  /* Sandy River Beach */,
             (9779::bigint)  /* Slackwater Beach */,
             (9797::bigint)  /* Windboarding Beachhead */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.fs.usda.gov/r06/columbiarivergorge/'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
