-- State-agency rule codify: Okanogan-Wenatchee National Forest Pet Policy - 36 CFR §261.16(j) (6-ft leash in developed sites)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Forest Service (id=292)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=USFS unit_name~'%wenatchee%'
-- Affected beaches: 2
--
--   fid 9809  Dog Beach
--   fid 9939  Speelyi Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'Okanogan-Wenatchee National Forest Pet Policy - 36 CFR §261.16(j) (6-ft leash in developed sites)',
       292,
       ARRAY['dog_policy']::text[],
       'https://www.fs.usda.gov/r06/okanogan-wenatchee/safety-ethics',
       'Okanogan-Wenatchee National Forest — Pet Policy

OPERATIVE RULE (USFS R6 standard):
- Developed recreation areas (campgrounds, picnic areas, trailheads): Pets must be on a hand-held leash no longer than 6 feet
- Backcountry/wilderness: Pets may be off-leash provided under voice control; on most trails dogs must be "under control at all times"
- Some designated Alpine Lakes Wilderness trails require leash (Exhibit F, 36 CFR §261.55(c))
- COMPLETE PROHIBITION: Enchantment Permit Area + Ingalls Lake area of Alpine Lakes Wilderness (except service dogs)

For PAD-US-tagged beaches within the forest (typically reservoir/lake beach access points in developed recreation areas), the on_leash 6-ft rule applies.

Citation: Okanogan-Wenatchee National Forest Pet Policy + 36 CFR §261.16(j) + Forest Order 06-17-1994-001
URL: https://www.fs.usda.gov/r06/okanogan-wenatchee/safety-ethics
Verbatim: "In developed sites such as campgrounds and picnic areas, dogs must always be restrained or on a leash no more than 6 feet long."
Subtype: agency_administrative_policy

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'agent_dispatch_2026_05_18_afk')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.fs.usda.gov/r06/okanogan-wenatchee/safety-ethics'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       '6-ft leash in developed sites',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9809::bigint)  /* Dog Beach */,
             (9939::bigint)  /* Speelyi Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.fs.usda.gov/r06/okanogan-wenatchee/safety-ethics'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
