-- State-agency rule codify: Ebey's Landing National Historical Reserve Pets Policy (NPS partnership reserve — on-leash on all trails + beaches)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: National Park Service (id=307)
-- Subtype: agency_administrative_policy
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=NPS unit_name~'%ebey%'
-- Affected beaches: 11
--
--   fid 17749206  Coupeville Beach
--   fid 14289721  Keystone Beach Tidelands
--   fid 12121133  Long Point Beach
--   fid 17164995  Monroe Landing
--   fid 13467762  Penn Cove / Madrona
--   fid 2749840  Penn Cove Beach
--   fid 9839511  Penn Cove Tidelands
--   fid 4383988  San De Fuca
--   fid 19659713  South Ebey's Landing
--   fid 13945973  W. Penn Cove Beach
--   fid 9616742  West Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'agency_administrative_policy',
       'Ebey''s Landing National Historical Reserve Pets Policy (NPS partnership reserve — on-leash on all trails + beaches)',
       307,
       ARRAY['dog_policy']::text[],
       'https://www.nps.gov/ebla/planyourvisit/pets.htm',
       'Ebey''s Landing National Historical Reserve — Pets Policy

OPERATIVE RULE: Dogs must remain on-leash on all Reserve trails to protect wildlife, visitors, and landowners. The reserve enforces responsible pet ownership through B.A.R.K. principles: Bag waste and pack it out, Always wear a leash (keeping dogs on designated areas), Respect wildlife and hikers, and Know where you can go. Pets are welcome on Reserve beaches, but owners must pack out all pet waste.

Reserve context: 85%+ of land is privately owned; dogs must not roam onto private property or chase wildlife.

Citation: Ebey''s Landing National Historical Reserve Pets Policy (NPS official page)
URL: https://www.nps.gov/ebla/planyourvisit/pets.htm
Verbatim: "Dogs must remain on-leash on all Reserve trails. Pets are welcome on Reserve beaches, but owners must pack out all pet waste."

Subtype: agency_administrative_policy (partnership reserve policy; NPS + Town of Coupeville + Island County + Washington State Parks). The reserve does not appear to have a formal Superintendent''s Compendium PDF; the policy is published directly on the NPS pets page.

Off-leash carve-out (separate facility): Patmore Off-Leash Area — 10-acre county-managed off-leash dog park within the reserve boundary. Not part of the 11 PAD-US-tagged beaches.

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       NULL
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.nps.gov/ebla/planyourvisit/pets.htm'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'Ebey''s Landing NHR: ''Dogs must remain on-leash on all Reserve trails. Pets are welcome on Reserve beaches, but owners must pack out all pet waste.''',
       ps.source_url, NOW(), NOW()
FROM (VALUES (17749206::bigint)  /* Coupeville Beach */,
             (14289721::bigint)  /* Keystone Beach Tidelands */,
             (12121133::bigint)  /* Long Point Beach */,
             (17164995::bigint)  /* Monroe Landing */,
             (13467762::bigint)  /* Penn Cove / Madrona */,
             (2749840::bigint)  /* Penn Cove Beach */,
             (9839511::bigint)  /* Penn Cove Tidelands */,
             (4383988::bigint)  /* San De Fuca */,
             (19659713::bigint)  /* South Ebey's Landing */,
             (13945973::bigint)  /* W. Penn Cove Beach */,
             (9616742::bigint)  /* West Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.nps.gov/ebla/planyourvisit/pets.htm'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
