-- Remediation of root-URL violations per [[ca-root-url-discipline-violation]]
-- Generated by sub-agent dispatch 2026-05-18.
--
-- Scope: 14 CA policy_source rows surfaced by the CA codify-v1 review as genuine
-- page-level URL discipline violations. 12 fixed with discovered deep links; 2
-- left as-is (operator/PDF acceptable) with audit-trail comments; 1 deferred
-- (Yurok tribal — per Franz's defer instruction in the pin).
--
-- Per-row audit trail follows. Every new URL must include one of the deep-link
-- markers from the pin's table (?nodeId=, #anchor, .pdf, /section-N.M,
-- ecode360.com/<numeric>, library.qcode.us/.../item/<section>, etc.).

BEGIN;

-- ----------------------------------------------------------------------------
-- Row 22 — City of Long Beach Rosie's Dog Beach published rules
-- Category C — ACCEPTABLE-AS-IS (operator_posted_policy)
-- Current: https://www.longbeach.gov/park/park-and-facilities/directory/rosies-dog-beach/
-- Reasoning: subtype is operator_posted_policy and the city park directory page
-- IS the operative source for the operator-posted rules at this beach. Pin
-- explicitly flags this row as "borderline — operator post IS the source".
-- NO UPDATE.
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- Row 52 — Yurok Tribal Code — animal access provisions (section TBD)
-- Category C — DEFER (per Franz, tribal codification deferred)
-- Current: https://www.yuroktribe.org
-- DEFER: tribal_code subtype, target section not yet identified. Per the pin
--        and Franz's prior guidance, tribal-code codification is deferred from
--        the CA codify-v1 push. Leave source_url unchanged until the Yurok
--        codification work is reopened.
-- NO UPDATE.
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- Row 90 — 43 CFR §8365.2-1 + §8365.2-5 (BLM Developed Recreation Sites)
-- Category B — combined-citation; one URL covers both sections
-- Before: https://www.ecfr.gov/current/title-43/subtitle-B/chapter-II/subchapter-H/part-8360/subpart-8365
-- After:  https://www.ecfr.gov/current/title-43/subtitle-B/chapter-II/subchapter-H/part-8360/subpart-8365/section-8365.2-5
-- Why:    §8365.2-5 (Public health, safety and comfort) is the operative
--         no-pets-in-swimming-areas provision most relevant to dog-on-beach
--         policy; cited alongside §8365.2-1 in the citation string. Per the
--         brief, accepting one URL for combined-citation cases is acceptable.
--         eCFR /section-N.M pattern satisfies the deep-link regex.
UPDATE public.policy_source
SET source_url = 'https://www.ecfr.gov/current/title-43/subtitle-B/chapter-II/subchapter-H/part-8360/subpart-8365/section-8365.2-5'
WHERE id = 90
  AND source_url = 'https://www.ecfr.gov/current/title-43/subtitle-B/chapter-II/subchapter-H/part-8360/subpart-8365';

-- ----------------------------------------------------------------------------
-- Row 106 — Sutter County Code — Animal Regulation Chapter
-- Category A — FIX
-- Before: https://library.municode.com/ca/sutter_county/codes/code_of_ordinances
-- After:  https://library.municode.com/ca/sutter_county/codes/code_of_ordinances?nodeId=n800AN
-- Why:    Sutter County's animal regulations live under Municode node "n800AN"
--         (Chapter 800 — ANIMALS). Adds the ?nodeId= deep-link the pin requires.
UPDATE public.policy_source
SET source_url = 'https://library.municode.com/ca/sutter_county/codes/code_of_ordinances?nodeId=n800AN'
WHERE id = 106
  AND source_url = 'https://library.municode.com/ca/sutter_county/codes/code_of_ordinances';

-- ----------------------------------------------------------------------------
-- Row 108 — Yuba County Code — Animal Regulation Chapter
-- Category A — FIX
-- Before: https://library.municode.com/ca/yuba_county/codes/code_of_ordinances
-- After:  https://library.municode.com/ca/yuba_county/codes/code_of_ordinances?nodeId=TITVIIIPUPESA_CH8.05ANCASE
-- Why:    Yuba County animal regulations live in Title VIII Chapter 8.05
--         (ANIMAL CARE SERVICES). Adds ?nodeId= deep link.
UPDATE public.policy_source
SET source_url = 'https://library.municode.com/ca/yuba_county/codes/code_of_ordinances?nodeId=TITVIIIPUPESA_CH8.05ANCASE'
WHERE id = 108
  AND source_url = 'https://library.municode.com/ca/yuba_county/codes/code_of_ordinances';

-- ----------------------------------------------------------------------------
-- Row 143 — Half Moon Bay Municipal Code §9.13.020 (Designated parks and beaches)
-- Category A — FIX
-- Before: https://www.halfmoonbay.gov/438/Beaches
-- After:  https://www.codepublishing.com/CA/HalfMoonBay/html/HalfMoonBay09/HalfMoonBay0913.html#47028750
-- Why:    Replaces the city "Beaches" landing page (not a codified source) with
--         the codepublishing chapter URL anchored at §9.13.020's numeric ID
--         (#47028750) discovered via Playwright fetch of the chapter page.
UPDATE public.policy_source
SET source_url = 'https://www.codepublishing.com/CA/HalfMoonBay/html/HalfMoonBay09/HalfMoonBay0913.html#47028750'
WHERE id = 143
  AND source_url = 'https://www.halfmoonbay.gov/438/Beaches';

-- ----------------------------------------------------------------------------
-- Row 155 — City of San Clemente — citywide dogs-on-beach prohibition
-- Category D — FIX (replace OC Register news article with actual MC section)
-- Before: https://www.ocregister.com/2014/03/19/san-clemente-opens-nearly-all-parks-to-dogs/
-- After:  https://library.municode.com/ca/san_clemente/codes/code_of_ordinances?nodeId=TIT6AN_CH6.10REBADO_6.10.080HEPR
-- Why:    A news article is not a codified policy source. San Clemente MC
--         §6.10.080 (Title 6 Animals, Ch 6.10 Recreational/Beach/Dog Ordinance,
--         §6.10.080 Health Prohibition) is the citywide dogs-on-beach
--         prohibition. Discovered via WebSearch of Municode San Clemente.
UPDATE public.policy_source
SET source_url = 'https://library.municode.com/ca/san_clemente/codes/code_of_ordinances?nodeId=TIT6AN_CH6.10REBADO_6.10.080HEPR'
WHERE id = 155
  AND source_url = 'https://www.ocregister.com/2014/03/19/san-clemente-opens-nearly-all-parks-to-dogs/';

-- ----------------------------------------------------------------------------
-- Row 158 — Santa Barbara Municipal Code §6.08.070 (Animals - Public Beaches and Harbor)
-- Category A — FIX
-- Before: https://santabarbaraca.gov/government/departments/santa-barbara-police-department/city-animal-regulations
-- After:  https://ecode360.com/44099511
-- Why:    Replaces the police-department city-animal-regulations landing page
--         with the ecode360 numeric-ID deep link for §6.08.070, discovered by
--         locating data-guid="44099511" on the chapter page. Santa Barbara MC
--         has migrated from qcode to ecode360 (qcode URLs 301 to resolve.ecode360).
UPDATE public.policy_source
SET source_url = 'https://ecode360.com/44099511'
WHERE id = 158
  AND source_url = 'https://santabarbaraca.gov/government/departments/santa-barbara-police-department/city-animal-regulations';

-- ----------------------------------------------------------------------------
-- Row 161 — Sausalito Municipal Code §6.04.160 (Citywide leash law)
-- Category A — FIX
-- Before: https://ecode360.com/SA4880
-- After:  https://ecode360.com/47133309
-- Why:    Replaces the ecode360 table-of-contents slug (SA4880) with the
--         numeric section ID 47133309 for §6.04.160, discovered via the
--         codepublishing chapter page (codepublishing and ecode360 share
--         General Code's internal numeric IDs).
UPDATE public.policy_source
SET source_url = 'https://ecode360.com/47133309'
WHERE id = 161
  AND source_url = 'https://ecode360.com/SA4880';

-- ----------------------------------------------------------------------------
-- Row 181 — Santa Cruz County Code §6.12.020 (Dogs off premises — leash required)
-- Category A — FIX
-- Before: https://www.animallaw.info/local/ca-santa-cruz-county-santa-cruz-county-code-title-6-animals
-- After:  https://www.codepublishing.com/CA/SantaCruzCounty/html/SantaCruzCounty06/SantaCruzCounty0612.html#47524370
-- Why:    Replaces the third-party animallaw.info mirror with the official
--         county code on codepublishing.com, anchored at §6.12.020's numeric
--         ID (#47524370) discovered via Playwright fetch of Chapter 6.12.
UPDATE public.policy_source
SET source_url = 'https://www.codepublishing.com/CA/SantaCruzCounty/html/SantaCruzCounty06/SantaCruzCounty0612.html#47524370'
WHERE id = 181
  AND source_url = 'https://www.animallaw.info/local/ca-santa-cruz-county-santa-cruz-county-code-title-6-animals';

-- ----------------------------------------------------------------------------
-- Row 182 — Tuolumne County Code §6.04.280 + §6.04.020(E,T)
-- Category C — ACCEPTABLE-AS-IS (PDF source)
-- Current: https://www.tuolumnecounty.ca.gov/DocumentCenter/View/312/Chapter-604---Animal-Control
-- Reasoning: PDF documents satisfy the deep-link discipline (they ARE the
-- source document). Could add #page= anchor for finer granularity but the
-- DocumentCenter PDF endpoint serves the whole Chapter 6.04 — section-level
-- page anchors not reliably navigable inside Tuolumne County's PDF viewer.
-- NO UPDATE. (Pin notes "optional #page=N anchor" as nice-to-have, not required.)
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- Row 223 — Redondo Beach Municipal Code §5-1.103 (Dogs running at large)
-- Category A — FIX
-- Before: https://library.qcode.us/lib/redondo_beach_ca/pub/municipal_code/item/title_5-chapter_1-5_1_103
-- After:  https://ecode360.com/42651572#42651572
-- Why:    Redondo Beach MC has migrated from qcode to ecode360 (qcode URL 301s
--         to resolve.ecode360). §5-1.103's ecode360 numeric ID is 42651572,
--         discovered via cross-reference on the Article 1 (Dogs) chapter page.
UPDATE public.policy_source
SET source_url = 'https://ecode360.com/42651572#42651572'
WHERE id = 223
  AND source_url = 'https://library.qcode.us/lib/redondo_beach_ca/pub/municipal_code/item/title_5-chapter_1-5_1_103';

-- ----------------------------------------------------------------------------
-- Row 232 — Trinidad Municipal Code Title 6 Ch 6.04 (DOGS)
-- Category A — FIX
-- Before: https://www.trinidad.ca.gov/animal-control
-- After:  https://www.codepublishing.com/CA/Trinidad/html/Trinidad06/Trinidad0604.html#6.04.050
-- Why:    Replaces the city animal-control landing page with the codepublishing
--         chapter URL anchored at §6.04.050 (Confinement of dogs to owner's
--         premises) — the operative leash provision. Trinidad uses readable
--         #6.04.NNN anchors (legacy codepublishing format).
UPDATE public.policy_source
SET source_url = 'https://www.codepublishing.com/CA/Trinidad/html/Trinidad06/Trinidad0604.html#6.04.050'
WHERE id = 232
  AND source_url = 'https://www.trinidad.ca.gov/animal-control';

-- ----------------------------------------------------------------------------
-- Row 235 — San Diego Unified Port District Code §8.02 (Park Areas Regulated)
-- Category A — FIX
-- Before: https://www.portofsandiego.org/parks-faq
-- After:  https://pantheonstorage.blob.core.windows.net/administration/Port-Code-Section-802.pdf
-- Why:    Replaces the parks-FAQ landing page with the Port's official PDF of
--         Port Code Section 8.02 itself. PDF satisfies deep-link discipline.
UPDATE public.policy_source
SET source_url = 'https://pantheonstorage.blob.core.windows.net/administration/Port-Code-Section-802.pdf'
WHERE id = 235
  AND source_url = 'https://www.portofsandiego.org/parks-faq';

-- ----------------------------------------------------------------------------
-- Sanity gate before commit
-- ----------------------------------------------------------------------------
SELECT id, substring(citation,1,60) AS citation, source_url
FROM public.policy_source
WHERE id IN (22, 52, 90, 106, 108, 143, 155, 158, 161, 181, 182, 223, 232, 235)
ORDER BY id;

COMMIT;
