-- State-agency rule codify: 36 CFR §2.15 (Pets) — National Park Service, Ch. I Part 2 (Resource Protection, Public Use and Recreation)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: National Park Service (id=307)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  CA,OR,WA
-- PAD-US filter: mng_type=FED mng_name=NPS
-- Affected beaches: 30
--
--   fid 17159836  Apple Beach
--   fid 8273662  Beach 2
--   fid 9827  Beach 3
--   fid 15029295  Bradbury Beach
--   fid 17749206  Coupeville Beach
--   fid 16669115  Crescent Bay On Lake Roosevelt
--   fid 16890883  Fort Spokane Swim Beach
--   fid 8867735  Kalaloch Beach
--   fid 9813  Kalaloch Beach 1
--   fid 18252728  Kayostia Beach
--   fid 14289721  Keystone Beach Tidelands
--   fid 982839  Lake Crescent - East Beach
--   fid 12121133  Long Point Beach
--   fid 17164995  Monroe Landing
--   fid 13467762  Penn Cove / Madrona
--   fid 2749840  Penn Cove Beach
--   fid 9839511  Penn Cove Tidelands
--   fid 16311068  Rialto Beach
--   fid 9928  Richwine Gravel Bar
--   fid 17477482  Ruby Beach
--   fid 4383988  San De Fuca
--   fid 18712551  Second Beach
--   fid 1147939  Shi Shi Beach
--   fid 9872  South Beach
--   fid 19659713  South Ebey's Landing
--   fid 17566883  The Colville Flats
--   fid 9616888  Third Beach Trailhead (Strawberry Bay Falls)
--   fid 13945973  W. Penn Cove Beach
--   fid 9849  Waikiki Beach
--   fid 9616742  West Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       '36 CFR §2.15 (Pets) — National Park Service, Ch. I Part 2 (Resource Protection, Public Use and Recreation)',
       307,
       ARRAY['dog_policy']::text[],
       'https://www.ecfr.gov/current/title-36/chapter-I/part-2/section-2.15',
       '36 CFR §2.15 Pets

(a) The following are prohibited:
  (1) Possessing a pet in a public building, public transportation vehicle, or location designated as a swimming beach, or any structure or area closed to the possession of pets by the superintendent. This subparagraph shall not apply to guide dogs accompanying visually impaired persons or hearing ear dogs accompanying hearing-impaired persons.
  (2) Failing to crate, cage, restrain on a leash which shall not exceed six feet in length, or otherwise physically confine a pet at all times.
  (3) Leaving a pet unattended and tied to an object, except in pet picket areas designated by the superintendent.
  (4) Allowing a pet to make noise that is unreasonable considering location, time of day or night, impact on park users, and other relevant factors or that frightens wildlife by barking, howling, or making other noise.

(b) Pets may not be used to pursue, kill, or capture park wildlife.

(c) Pets may be kept by residents of park areas in accordance with the conditions which may be established by the superintendent.

(d) The disposition of unattended pets and pets observed engaged in any of the activities prohibited by paragraph (a) of this section is governed by §2.15(a).

(e) Pets, except for guide dogs and hearing ear dogs, may be excluded from public buildings.

(f) Dogs and cats running-at-large in a park area may be impounded.

(g) Violation of the terms and conditions of a permit issued in accordance with §1.6 is prohibited and may result in the suspension or revocation of the permit.

Operative defaults for NPS-managed park beaches under 36 CFR §2.15:
- on_leash (max 6 ft) per §(a)(2) — DEFAULT
- not_allowed at designated swim areas + adjacent beaches per §(a)(1)
- not_allowed at any area closed to pets by superintendent per §(a)(1)
- Superintendents may further restrict via Compendium (e.g., Olympic NP, GGNRA Fort Funston, Cape Hatteras)

Citation: 36 CFR Chapter I, Part 2 (Resource Protection, Public Use and Recreation), Section 2.15 (Pets). Issuing agency: National Park Service.

Per [[walkthrough-fort-funston]] superintendents_compendium is the per-unit subtype that OVERRIDES this baseline. Per-unit compendiums supersede the CFR baseline within that unit. Use 36 CFR §2.15 as the federal baseline only; emit per-unit compendiums separately.

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       '1983-06-30'::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'auto_encapsulated_2026_05_18', 'federal_baseline', 'true', 'per_unit_override_subtype', 'superintendents_compendium')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.ecfr.gov/current/title-36/chapter-I/part-2/section-2.15'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       '36 CFR §2.15(a)(2): Failing to crate, cage, restrain on a leash which shall not exceed six feet in length, or otherwise physically confine a pet at all times — prohibited. §(a)(1) prohibits pets at designated swimming beaches and superintendent-closed areas.',
       ps.source_url, NOW(), NOW()
FROM (VALUES (17159836::bigint)  /* Apple Beach */,
             (8273662::bigint)  /* Beach 2 */,
             (9827::bigint)  /* Beach 3 */,
             (15029295::bigint)  /* Bradbury Beach */,
             (17749206::bigint)  /* Coupeville Beach */,
             (16669115::bigint)  /* Crescent Bay On Lake Roosevelt */,
             (16890883::bigint)  /* Fort Spokane Swim Beach */,
             (8867735::bigint)  /* Kalaloch Beach */,
             (9813::bigint)  /* Kalaloch Beach 1 */,
             (18252728::bigint)  /* Kayostia Beach */,
             (14289721::bigint)  /* Keystone Beach Tidelands */,
             (982839::bigint)  /* Lake Crescent - East Beach */,
             (12121133::bigint)  /* Long Point Beach */,
             (17164995::bigint)  /* Monroe Landing */,
             (13467762::bigint)  /* Penn Cove / Madrona */,
             (2749840::bigint)  /* Penn Cove Beach */,
             (9839511::bigint)  /* Penn Cove Tidelands */,
             (16311068::bigint)  /* Rialto Beach */,
             (9928::bigint)  /* Richwine Gravel Bar */,
             (17477482::bigint)  /* Ruby Beach */,
             (4383988::bigint)  /* San De Fuca */,
             (18712551::bigint)  /* Second Beach */,
             (1147939::bigint)  /* Shi Shi Beach */,
             (9872::bigint)  /* South Beach */,
             (19659713::bigint)  /* South Ebey's Landing */,
             (17566883::bigint)  /* The Colville Flats */,
             (9616888::bigint)  /* Third Beach Trailhead (Strawberry Bay Falls) */,
             (13945973::bigint)  /* W. Penn Cove Beach */,
             (9849::bigint)  /* Waikiki Beach */,
             (9616742::bigint)  /* West Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.ecfr.gov/current/title-36/chapter-I/part-2/section-2.15'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
