-- State-agency rule codify: Lake Roosevelt NRA Superintendent's Compendium (Pets)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-19
--
-- Agency: National Park Service (id=307)
-- Subtype: superintendents_compendium
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=NPS unit_name~'%Lake Roosevelt%'
-- Affected beaches: 5
--
--   fid 17159836  Apple Beach
--   fid 15029295  Bradbury Beach
--   fid 16669115  Crescent Bay On Lake Roosevelt
--   fid 16890883  Fort Spokane Swim Beach
--   fid 17566883  The Colville Flats
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'superintendents_compendium',
       'Lake Roosevelt NRA Superintendent''s Compendium (Pets)',
       307,
       ARRAY['dog_policy']::text[],
       'https://www.nps.gov/laro/planyourvisit/pets.htm',
       'Source: National Park Service — Lake Roosevelt National Recreation Area, Pets page
URL: https://www.nps.gov/laro/planyourvisit/pets.htm
Fetched: 2026-05-19 via WebFetch
Baseline authority: 36 CFR §2.15 (Pets)
Associated Compendium: https://www.nps.gov/laro/learn/management/upload/2025-Compendium-v4_4-DEC-25-508CR.pdf
Associated Laws & Policies page: https://www.nps.gov/laro/learn/management/lawsandpolicies.htm

=== VERBATIM TEXT ===

Pets at Lake Roosevelt National Recreation Area

"Dogs are allowed in the park, except in developed swim beach areas, as long as they wear their leash."

"Please stay on a leash no more than 6 feet long."

"Barking dogs are considered a nuisances and owners must remove them from the campground."

"Never leave your pet in a closed vehicle. Temperatures can soar to 130F (55C) in minutes."

"Bag your poop! Keep our park a clean and healthy place to visit."

"Respect wildlife! You are visiting the homes of other animals when walking around Lake Roosevelt. Please stay on the trails and be respectful. Please, no chasing any animals you may encounter."

The park references Code of Federal Regulations 36 CFR §2.15 for complete regulatory details.

=== KEY OPERATIVE QUOTE FOR EVIDENCE ===

"Dogs are allowed in the park, except in developed swim beach areas, as long as they wear their leash. Please stay on a leash no more than 6 feet long."

=== INTERPRETATION ===

- Base rule: on_leash (6-foot max leash, consistent with 36 CFR §2.15(a)(2))
- Carve-out: dogs NOT allowed in developed swim beach areas
- This is the NPS standard pattern (more permissive than NP units, typical of NRAs)
- Beaches in scope are the 5 LARO-area beaches per PAD-US (Apple Beach, Bradbury Beach,
  Crescent Bay On Lake Roosevelt, Fort Spokane Swim Beach, The Colville Flats). Per-beach
  decisions about "developed swim beach" vs general shoreline can be captured via
  status_note if needed.

[Codified via codify v1 --state-agency-rule 2026-05-19.]',
       NULL::date,
       NOW(),
       NULL
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.nps.gov/laro/planyourvisit/pets.htm'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'Dogs are allowed in the park, except in developed swim beach areas, as long as they wear their leash. Please stay on a leash no more than 6 feet long.',
       ps.source_url, NOW(), NOW()
FROM (VALUES (17159836::bigint)  /* Apple Beach */,
             (15029295::bigint)  /* Bradbury Beach */,
             (16669115::bigint)  /* Crescent Bay On Lake Roosevelt */,
             (16890883::bigint)  /* Fort Spokane Swim Beach */,
             (17566883::bigint)  /* The Colville Flats */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.nps.gov/laro/planyourvisit/pets.htm'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
