-- State-agency rule codify: BLM San Juan Islands National Monument Resource Management Plan (2023) Appendix F (Recreation Management Areas) — Pets — RoD 2023-01971
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Bureau of Land Management (id=288)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=BLM unit_name~'%san juan%national monument%'
-- Affected beaches: 50
--
--   fid 19744387  Blackie Brady County Park
--   fid 18334210  Cape Saint Mary
--   fid 15084206  Cattle Point Beach
--   fid 2859489  Center Island Recreation Site
--   fid 5951373  Chin-Chin-Tse-Tung
--   fid 9891  Cottonwood Cove
--   fid 9941  Crescent Beach
--   fid 8459759  Deer Harbor, Beach 240b
--   fid 13110980  Double Island, Beach 251a
--   fid 9890  Driftwood Beach
--   fid 3337203  Eagle Cove
--   fid 10921112  Eagle Cove
--   fid 6459682  Flint Beach
--   fid 9909  Fourth of July Beach
--   fid 14352074  Friday Harbor Labs
--   fid 9896  Green Bank
--   fid 9922  Haida Canoe Cove
--   fid 6649715  Jackson Beach
--   fid 9800  Kimple Beach
--   fid 13344146  Little Sucia Island, Beach 367d
--   fid 10105173  Lopez Rd End
--   fid 9817  Madrona Beach
--   fid 9412646  Mt. Shadows Homeowners Beach
--   fid 10119588  N Blakely Island
--   fid 15983013  N Spencer Spit
--   fid 9884  Nawalagwis (Magic Beach)
--   fid 9873  North Beach
--   fid 9885  North Beach
--   fid 7678724  North Finger Island, Beach 367b
--   fid 9570833  Northwest Decatur Island
--   fid 9850  Obstruction Pass Beach
--   fid 2992949  Pelican Beach
--   fid 4889758  Pole Island
--   fid 19875474  San Juan Preservation Trust, Henry Island
--   fid 13875763  Shaw Landing
--   fid 7635568  Sinclair Island Lighthouse, Beach 213a
--   fid 2145733  Sisters Islets
--   fid 9872  South Beach
--   fid 17406944  South Beach
--   fid 19146962  Spencer Spit State Park Beach
--   fid 8374710  Spieden Island, Beach 352
--   fid 3736075  Stuart Island Marine State Park Beach
--   fid 9881  Sunrise Beach
--   fid 9865  Sunset Beach
--   fid 661374  Sunset Beach
--   fid 9816  The Landing
--   fid 14049922  Turn Point Lighthouse
--   fid 16809125  Victim Island, Beach 251b
--   fid 18769592  Waldron Island Preserve
--   fid 9805  White Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'BLM San Juan Islands National Monument Resource Management Plan (2023) Appendix F (Recreation Management Areas) — Pets — RoD 2023-01971',
       288,
       ARRAY['dog_policy']::text[],
       'https://www.federalregister.gov/documents/2023/01/31/2023-01971/notice-of-availability-of-the-record-of-decision-and-approved-resource-management-plan-for-the-san',
       'BLM San Juan Islands National Monument Approved Resource Management Plan (2023)

Source: Federal Register Notice of Availability of the Record of Decision and Approved Resource Management Plan for the San Juan Islands National Monument, Washington (2023-01971; signed January 26, 2023).
URL: https://www.federalregister.gov/documents/2023/01/31/2023-01971/notice-of-availability-of-the-record-of-decision-and-approved-resource-management-plan-for-the-san

OPERATIVE RULE (from RMP Appendix F — Recreation Management Areas):
- Default: on_leash
- "Unleashed pets" permitted in some specific recreation management areas; "Leashed pets" required in most other areas
- Per-area variations per Appendix F (curator review for specific RMA assignments per beach)

Context:
- BLM San Juan Islands NM was designated by Presidential Proclamation 8947 (March 25, 2013)
- Covers ~1,000 acres across 75 islands, rocks, and reefs in WA''s San Juan archipelago
- Includes BLM-managed parcels on Patos, Stuart, Lopez, San Juan, Blakely, and other islands
- PAD-US-tagged beach overlap: 50 beaches in WA
- Wildlife protection drives most pet restrictions (seabird nesting, marine mammal haulouts)

CITATION: BLM San Juan Islands National Monument Resource Management Plan (2023) Appendix F (Recreation Management Areas) — on-leash pet requirement
URL: https://www.federalregister.gov/documents/2023/01/31/2023-01971/notice-of-availability-of-the-record-of-decision-and-approved-resource-management-plan-for-the-san
VERBATIM: "Unleashed pets (some areas allow leashed pets)" — operative rule per the RMP RMA-specific allowances (Appendix F).

Per-area refinement opportunity: curator can override specific beaches whose BLM RMA assignment permits unleashed pets vs requires leash. Default ship: on_leash with status_note flagging the per-RMA variability for curator review.

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       '2023-01-26'::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'agent_dispatch_2026_05_18', 'multi_rma_variability', 'true', 'curator_review_for_per_rma_refinement', 'true')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.federalregister.gov/documents/2023/01/31/2023-01971/notice-of-availability-of-the-record-of-decision-and-approved-resource-management-plan-for-the-san'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'BLM SJINM RMP (2023) Appendix F: Unleashed pets permitted in some areas; leashed pets required in most other areas. Per-RMA variability; default on_leash with status_note for curator review per beach.',
       ps.source_url, NOW(), NOW()
FROM (VALUES (19744387::bigint)  /* Blackie Brady County Park */,
             (18334210::bigint)  /* Cape Saint Mary */,
             (15084206::bigint)  /* Cattle Point Beach */,
             (2859489::bigint)  /* Center Island Recreation Site */,
             (5951373::bigint)  /* Chin-Chin-Tse-Tung */,
             (9891::bigint)  /* Cottonwood Cove */,
             (9941::bigint)  /* Crescent Beach */,
             (8459759::bigint)  /* Deer Harbor, Beach 240b */,
             (13110980::bigint)  /* Double Island, Beach 251a */,
             (9890::bigint)  /* Driftwood Beach */,
             (3337203::bigint)  /* Eagle Cove */,
             (10921112::bigint)  /* Eagle Cove */,
             (6459682::bigint)  /* Flint Beach */,
             (9909::bigint)  /* Fourth of July Beach */,
             (14352074::bigint)  /* Friday Harbor Labs */,
             (9896::bigint)  /* Green Bank */,
             (9922::bigint)  /* Haida Canoe Cove */,
             (6649715::bigint)  /* Jackson Beach */,
             (9800::bigint)  /* Kimple Beach */,
             (13344146::bigint)  /* Little Sucia Island, Beach 367d */,
             (10105173::bigint)  /* Lopez Rd End */,
             (9817::bigint)  /* Madrona Beach */,
             (9412646::bigint)  /* Mt. Shadows Homeowners Beach */,
             (10119588::bigint)  /* N Blakely Island */,
             (15983013::bigint)  /* N Spencer Spit */,
             (9884::bigint)  /* Nawalagwis (Magic Beach) */,
             (9873::bigint)  /* North Beach */,
             (9885::bigint)  /* North Beach */,
             (7678724::bigint)  /* North Finger Island, Beach 367b */,
             (9570833::bigint)  /* Northwest Decatur Island */,
             (9850::bigint)  /* Obstruction Pass Beach */,
             (2992949::bigint)  /* Pelican Beach */,
             (4889758::bigint)  /* Pole Island */,
             (19875474::bigint)  /* San Juan Preservation Trust, Henry Island */,
             (13875763::bigint)  /* Shaw Landing */,
             (7635568::bigint)  /* Sinclair Island Lighthouse, Beach 213a */,
             (2145733::bigint)  /* Sisters Islets */,
             (9872::bigint)  /* South Beach */,
             (17406944::bigint)  /* South Beach */,
             (19146962::bigint)  /* Spencer Spit State Park Beach */,
             (8374710::bigint)  /* Spieden Island, Beach 352 */,
             (3736075::bigint)  /* Stuart Island Marine State Park Beach */,
             (9881::bigint)  /* Sunrise Beach */,
             (9865::bigint)  /* Sunset Beach */,
             (661374::bigint)  /* Sunset Beach */,
             (9816::bigint)  /* The Landing */,
             (14049922::bigint)  /* Turn Point Lighthouse */,
             (16809125::bigint)  /* Victim Island, Beach 251b */,
             (18769592::bigint)  /* Waldron Island Preserve */,
             (9805::bigint)  /* White Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.federalregister.gov/documents/2023/01/31/2023-01971/notice-of-availability-of-the-record-of-decision-and-approved-resource-management-plan-for-the-san'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
