-- State-agency rule codify: San Juan Island National Historical Park Pets Policy (NPS — leashed pets allowed on all park trails + beaches; explicit override of 36 CFR §2.15 swim-beach prohibition)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: National Park Service (id=307)
-- Subtype: agency_administrative_policy
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=NPS unit_name~'%san juan island%historical%'
-- Affected beaches: 1
--
--   fid 9872  South Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'agency_administrative_policy',
       'San Juan Island National Historical Park Pets Policy (NPS — leashed pets allowed on all park trails + beaches; explicit override of 36 CFR §2.15 swim-beach prohibition)',
       307,
       ARRAY['dog_policy']::text[],
       'https://www.nps.gov/sajh/planyourvisit/pets.htm',
       'San Juan Island National Historical Park — Pets Policy

OPERATIVE RULE: Leashed pets are allowed on all park trails and beaches. They are not allowed in any buildings. Leashes must not exceed 6 feet in length to prevent startling wildlife.

B.A.R.K. principles: Bag waste; Always wear a leash; Respect wildlife (observe from distance); Know where you can go.

Citation: San Juan Island National Historical Park Pets Policy (NPS official page)
URL: https://www.nps.gov/sajh/planyourvisit/pets.htm
Verbatim: "Leashed pets are allowed on all park trails and beaches. They are not allowed in any buildings."

Subtype: agency_administrative_policy (supported by Superintendent''s Compendium at nps.gov/sajh/learn/management/superintendent-s-compendium.htm).

KEY OVERRIDE vs 36 CFR §2.15 baseline:
- The CFR §2.15(a)(1) baseline PROHIBITS pets at "designated swimming beaches" + "structure or area closed by superintendent"
- SAJH explicitly permits leashed dogs on "all park trails and beaches", which includes American Camp South Beach (historically a popular dog-walking area)
- Effective override: on_leash everywhere, even on beach areas the federal baseline would prohibit

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       NULL
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.nps.gov/sajh/planyourvisit/pets.htm'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'San Juan Island NHP: ''Leashed pets are allowed on all park trails and beaches. They are not allowed in any buildings.'' Leashes must not exceed 6 feet.',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9872::bigint)  /* South Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.nps.gov/sajh/planyourvisit/pets.htm'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
