-- State-agency rule codify: OAR 736-021-0070 (Pets and Other Animals) — Parks and Recreation Department, Ch. 736, Div. 21 Ocean Shore State Recreation Area Rules
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: Oregon Parks and Recreation Department (id=359)
-- Subtype: state_regulation
-- Rule:    off_leash_voice_control  (section=sand)
-- States:  OR
-- PAD-US filter: (none — all active beaches in listed states)
-- Affected beaches: 152
--
--   fid 9733  Agate Beach
--   fid 19253013  Agate Beach
--   fid 8574501  Agate Beach
--   fid 8464886  Arcadia Beach
--   fid 9740  Arizona Beach
--   fid 6960245  Bailey Beach
--   fid 9777  Baker Beach
--   fid 12111783  Bandon Beach
--   fid 9787  Bastendorff Beach
--   fid 9789  Beverly Beach
--   fid 9782  Big Stump Beach
--   fid 4093702  Broughton Beach
--   fid 8051162  Bullards Beach
--   fid 7168395  Bullards Beach State Park Beach
--   fid 3966561  Cannon Beach
--   fid 9711  Cannon Beach Ecola Creek Beach Access
--   fid 15239890  Cape Arago State Park Beach - South Cove
--   fid 9712  Cape Kiwanda County Park Beach Access
--   fid 6109665  Cape Lookout State Park
--   fid 9778  Chapman Beach
--   fid 14127264  China Beach
--   fid 15804469  Cobble Beach
--   fid 9760  Collins Beach
--   fid 9772  Columbia Beach
--   fid 14154320  Coquille Point
--   fid 9728  Cottonwood Beach
--   fid 13653872  Cove Beach
--   fid 9764  Crescent Beach
--   fid 17326257  D River Beach Wayside
--   fid 10489918  D River State Recreation Area
--   fid 8314398  D River State Recreation Area
--   fid 18868488  Dahl Beach
--   fid 7230275  Devil's Kitchen
--   fid 6188548  Devils Punchbowl
--   fid 10366896  Diamond Beach
--   fid 9770  Dibblees Beach
--   fid 1595420  Euchre Creek Beach
--   fid 12134818  Euchre Creek Beach
--   fid 19264612  Fogarty Creek
--   fid 9713  Fort Stevens SP Peter Iredale Access
--   fid 10204916  Gearhart Beach
--   fid 8315821  Glass Bar Nude Beach
--   fid 9725  Goble Beach
--   fid 17971443  Gold Beach
--   fid 9750  Harris Beach
--   fid 9780  Heceta Beach
--   fid 9767  Hobbit Beach
--   fid 9742  Holly Beach
--   fid 17883899  Hubbard Creek
--   fid 12936438  Hunter Creek S. Of Gold Beach
--   fid 12219332  Indian Beach
--   fid 17745235  Jennie's Beach
--   fid 9752  Jones Beach
--   fid 9747  Kiwanda Beach
--   fid 9771  Kiwanda Beach
--   fid 9757  Koberg Beach
--   fid 9726  Lighthouse Beach
--   fid 8943410  Lincoln Beach - Spot 51C
--   fid 9758  Lindbergh’s Beach
--   fid 9730  Lone Ranch Beach
--   fid 16011995  Lost Boy Beach
--   fid 6947591  Luhr Jensen Beach
--   fid 9724  Lyons Beach
--   fid 13089519  Manhattan Beach
--   fid 9336701  Manzanita Beach
--   fid 9784  Marina Beach
--   fid 9732  McNary Beach
--   fid 13886615  Mcphillips Beach
--   fid 9741  Merchants Beach
--   fid 9615021  Meyers Creek Beach
--   fid 9776  Mill Beach
--   fid 9786  Moolack Beach
--   fid 9746  Myrtle Point Public Beach
--   fid 1447801  Nehalem Beach
--   fid 8671274  Nelscott Beach
--   fid 9788  Neptune Beach
--   fid 2408794  Nesika Beach
--   fid 9763  Neskowin Beach
--   fid 9748  North Beach
--   fid 9729  North Beach
--   fid 8462071  Nw 15Th St. Beach Access
--   fid 12934882  NW 26th St Beach Access
--   fid 17202918  Nw 34Th St. Beach Access
--   fid 16502429  Nye Beach
--   fid 1439671  Ocean Beach
--   fid 6607870  Oceanside Beach State Wayside
--   fid 13266936  Olivia Beach
--   fid 9735  Ophir Beach
--   fid 7360587  Oregon Beach Rides Day Tours
--   fid 14377282  Oregon Coast Beach
--   fid 5675422  Oregon Coast Beach
--   fid 12304687  Oregon's Best Beach
--   fid 9765  Poet's Beach
--   fid 12424881  Port Point Beach
--   fid 9734  Red Mill Beach
--   fid 9762  Reeder Beach
--   fid 9753  Reeder Beach
--   fid 13369068  Roads End Beach
--   fid 9761  Rock Creek Beach
--   fid 9901770  Rockaway Beach
--   fid 9749  Roosevelt Beach
--   fid 9737  Sacchi Beach
--   fid 19066087  Sailboard Beach
--   fid 9738  San Salvador Beach
--   fid 13465021  Sand Dollar Beach
--   fid 1879831  Sand Lake Recreation Area
--   fid 9785  Sand Point Beach
--   fid 13450745  Sand Station Beach
--   fid 9745  Sandy River Beach
--   fid 9755  Searose Beach
--   fid 9759  Seaside Beach
--   fid 9768  Seaside Cove Beach
--   fid 9744  Secret Beach
--   fid 7989535  Short Beach
--   fid 9790  Short Sand Beach
--   fid 7778992  Short Sands Beach
--   fid 12343970  Siletz Bay Beach
--   fid 9766  Simpson Beach
--   fid 13057824  Sixes Beach
--   fid 9779  Slackwater Beach
--   fid 13230871  South Beach
--   fid 9751  South Beach
--   fid 17564872  South Jetty (South Beach)
--   fid 12651087  South Jetty Beach 3 Day Use
--   fid 2867841  South Jetty Eastside
--   fid 9714  South Jetty Siuslaw River Beach Access 1
--   fid 18681201  South Jettybeach
--   fid 9773  Sporthaven Beach
--   fid 9265450  Spouting Horn
--   fid 9781  Stonefield Beach
--   fid 13031052  Strawberry Hill Wayside
--   fid 3661839  Sunset Bay Beach
--   fid 13638705  Sunset Beach
--   fid 17251238  Sunset Beach State Recreation Site
--   fid 2555786  Sw 34Th St. Beach Access
--   fid 9783  Swim Beach
--   fid 13952025  Taft Bay
--   fid 8121027  Taft Beach
--   fid 9715  Tolovana Beach SRS
--   fid 9774  Trestle Beach
--   fid 1764302  Tunnel Beach
--   fid 9754  Turner Lake Beach Area
--   fid 9739  Wakeman Beach
--   fid 13704506  Walton Beach
--   fid 14173849  Warehouse Beach
--   fid 9736  Westport Beach
--   fid 9756  Whaleshead Beach
--   fid 9731  Whisky Run Beach
--   fid 11535337  Willow Bar Beach
--   fid 7832717  Wilson Beach
--   fid 9501133  Winchuck State Recreation Site
--   fid 519513  Yachats Ocean Road State Wayside
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'state_regulation',
       'OAR 736-021-0070 (Pets and Other Animals) — Parks and Recreation Department, Ch. 736, Div. 21 Ocean Shore State Recreation Area Rules',
       359,
       ARRAY['dog_policy']::text[],
       'https://oregon.public.law/rules/oar_736-021-0070',
       'OAR 736-021-0070 Pets and Other Animals

(1) Domestic animals, including saddle or pack animals, are allowed in the ocean shore state recreation area except as provided in OAR 736-021-0090 (Cultural, Historic, Natural and Wildlife Resources), 736-030-0005 (Prohibition of Horses and Other Livestock), 736-030-0010 (Prohibition of Dogs Off Leash), and as otherwise posted by the department.

(2) The handler of any domestic animal must be responsible for the animal''s behavior and must exercise direct control over the animal while in the ocean shore state recreation area.
  (a) "Direct control" means that the animal is within the unobstructed sight of the handler and responds to voice commands or other methods of control.
  (b) Domestic animal handlers must carry a leash or restraining device at all times while in the ocean shore state recreation area.
  (c) Domestic animal handlers must promptly leash animals at the request or order of a park employee.
  (d) Handlers must prevent their animals from harassing people, wildlife and other domestic animals.
  (e) Animals may not be hitched or confined in a manner that may cause damage to any natural resources on the ocean shore.
  (f) Handlers are responsible for the removal of the animal''s waste while in the ocean shore state recreation area.

(3) A park manager, ocean shore naturalist, or law enforcement officer may take any measure deemed necessary to protect ocean shore resources or to prevent interference by the animal with the safety, comfort, or well-being of any person.

Operative rule for OR Ocean Shore State Recreation Area beaches:
- off_leash_voice_control (direct control = sight + responds to voice commands)
- handler must carry leash, leash on request, prevent harassment, pick up waste
- exceptions per OAR 736-021-0090 (wildlife protection — incl. snowy plover seasonal closures), 736-030-0005 (livestock), 736-030-0010 (specific dogs-off-leash prohibitions)
- park-employee discretion to require leash at any time

This is MORE PERMISSIVE than OAR 736-010-0030 (general park areas) which mandates strict 6-ft leash. The ocean shore regime is its own thing per ORS 390 Ocean Shore Recreation Area Act.

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       '2020-01-01'::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'auto_encapsulated_2026_05_18', 'ocean_shore_regulatory_regime', 'oar_chapter_736_division_21')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://oregon.public.law/rules/oar_736-021-0070'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'off_leash_voice_control',
       'operative'::operative_status,
       'OAR 736-021-0070(2): handler must exercise direct control = within unobstructed sight + responds to voice commands; must carry leash; must promptly leash at park-employee request.',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9733::bigint)  /* Agate Beach */,
             (19253013::bigint)  /* Agate Beach */,
             (8574501::bigint)  /* Agate Beach */,
             (8464886::bigint)  /* Arcadia Beach */,
             (9740::bigint)  /* Arizona Beach */,
             (6960245::bigint)  /* Bailey Beach */,
             (9777::bigint)  /* Baker Beach */,
             (12111783::bigint)  /* Bandon Beach */,
             (9787::bigint)  /* Bastendorff Beach */,
             (9789::bigint)  /* Beverly Beach */,
             (9782::bigint)  /* Big Stump Beach */,
             (4093702::bigint)  /* Broughton Beach */,
             (8051162::bigint)  /* Bullards Beach */,
             (7168395::bigint)  /* Bullards Beach State Park Beach */,
             (3966561::bigint)  /* Cannon Beach */,
             (9711::bigint)  /* Cannon Beach Ecola Creek Beach Access */,
             (15239890::bigint)  /* Cape Arago State Park Beach - South Cove */,
             (9712::bigint)  /* Cape Kiwanda County Park Beach Access */,
             (6109665::bigint)  /* Cape Lookout State Park */,
             (9778::bigint)  /* Chapman Beach */,
             (14127264::bigint)  /* China Beach */,
             (15804469::bigint)  /* Cobble Beach */,
             (9760::bigint)  /* Collins Beach */,
             (9772::bigint)  /* Columbia Beach */,
             (14154320::bigint)  /* Coquille Point */,
             (9728::bigint)  /* Cottonwood Beach */,
             (13653872::bigint)  /* Cove Beach */,
             (9764::bigint)  /* Crescent Beach */,
             (17326257::bigint)  /* D River Beach Wayside */,
             (10489918::bigint)  /* D River State Recreation Area */,
             (8314398::bigint)  /* D River State Recreation Area */,
             (18868488::bigint)  /* Dahl Beach */,
             (7230275::bigint)  /* Devil's Kitchen */,
             (6188548::bigint)  /* Devils Punchbowl */,
             (10366896::bigint)  /* Diamond Beach */,
             (9770::bigint)  /* Dibblees Beach */,
             (1595420::bigint)  /* Euchre Creek Beach */,
             (12134818::bigint)  /* Euchre Creek Beach */,
             (19264612::bigint)  /* Fogarty Creek */,
             (9713::bigint)  /* Fort Stevens SP Peter Iredale Access */,
             (10204916::bigint)  /* Gearhart Beach */,
             (8315821::bigint)  /* Glass Bar Nude Beach */,
             (9725::bigint)  /* Goble Beach */,
             (17971443::bigint)  /* Gold Beach */,
             (9750::bigint)  /* Harris Beach */,
             (9780::bigint)  /* Heceta Beach */,
             (9767::bigint)  /* Hobbit Beach */,
             (9742::bigint)  /* Holly Beach */,
             (17883899::bigint)  /* Hubbard Creek */,
             (12936438::bigint)  /* Hunter Creek S. Of Gold Beach */,
             (12219332::bigint)  /* Indian Beach */,
             (17745235::bigint)  /* Jennie's Beach */,
             (9752::bigint)  /* Jones Beach */,
             (9747::bigint)  /* Kiwanda Beach */,
             (9771::bigint)  /* Kiwanda Beach */,
             (9757::bigint)  /* Koberg Beach */,
             (9726::bigint)  /* Lighthouse Beach */,
             (8943410::bigint)  /* Lincoln Beach - Spot 51C */,
             (9758::bigint)  /* Lindbergh’s Beach */,
             (9730::bigint)  /* Lone Ranch Beach */,
             (16011995::bigint)  /* Lost Boy Beach */,
             (6947591::bigint)  /* Luhr Jensen Beach */,
             (9724::bigint)  /* Lyons Beach */,
             (13089519::bigint)  /* Manhattan Beach */,
             (9336701::bigint)  /* Manzanita Beach */,
             (9784::bigint)  /* Marina Beach */,
             (9732::bigint)  /* McNary Beach */,
             (13886615::bigint)  /* Mcphillips Beach */,
             (9741::bigint)  /* Merchants Beach */,
             (9615021::bigint)  /* Meyers Creek Beach */,
             (9776::bigint)  /* Mill Beach */,
             (9786::bigint)  /* Moolack Beach */,
             (9746::bigint)  /* Myrtle Point Public Beach */,
             (1447801::bigint)  /* Nehalem Beach */,
             (8671274::bigint)  /* Nelscott Beach */,
             (9788::bigint)  /* Neptune Beach */,
             (2408794::bigint)  /* Nesika Beach */,
             (9763::bigint)  /* Neskowin Beach */,
             (9748::bigint)  /* North Beach */,
             (9729::bigint)  /* North Beach */,
             (8462071::bigint)  /* Nw 15Th St. Beach Access */,
             (12934882::bigint)  /* NW 26th St Beach Access */,
             (17202918::bigint)  /* Nw 34Th St. Beach Access */,
             (16502429::bigint)  /* Nye Beach */,
             (1439671::bigint)  /* Ocean Beach */,
             (6607870::bigint)  /* Oceanside Beach State Wayside */,
             (13266936::bigint)  /* Olivia Beach */,
             (9735::bigint)  /* Ophir Beach */,
             (7360587::bigint)  /* Oregon Beach Rides Day Tours */,
             (14377282::bigint)  /* Oregon Coast Beach */,
             (5675422::bigint)  /* Oregon Coast Beach */,
             (12304687::bigint)  /* Oregon's Best Beach */,
             (9765::bigint)  /* Poet's Beach */,
             (12424881::bigint)  /* Port Point Beach */,
             (9734::bigint)  /* Red Mill Beach */,
             (9762::bigint)  /* Reeder Beach */,
             (9753::bigint)  /* Reeder Beach */,
             (13369068::bigint)  /* Roads End Beach */,
             (9761::bigint)  /* Rock Creek Beach */,
             (9901770::bigint)  /* Rockaway Beach */,
             (9749::bigint)  /* Roosevelt Beach */,
             (9737::bigint)  /* Sacchi Beach */,
             (19066087::bigint)  /* Sailboard Beach */,
             (9738::bigint)  /* San Salvador Beach */,
             (13465021::bigint)  /* Sand Dollar Beach */,
             (1879831::bigint)  /* Sand Lake Recreation Area */,
             (9785::bigint)  /* Sand Point Beach */,
             (13450745::bigint)  /* Sand Station Beach */,
             (9745::bigint)  /* Sandy River Beach */,
             (9755::bigint)  /* Searose Beach */,
             (9759::bigint)  /* Seaside Beach */,
             (9768::bigint)  /* Seaside Cove Beach */,
             (9744::bigint)  /* Secret Beach */,
             (7989535::bigint)  /* Short Beach */,
             (9790::bigint)  /* Short Sand Beach */,
             (7778992::bigint)  /* Short Sands Beach */,
             (12343970::bigint)  /* Siletz Bay Beach */,
             (9766::bigint)  /* Simpson Beach */,
             (13057824::bigint)  /* Sixes Beach */,
             (9779::bigint)  /* Slackwater Beach */,
             (13230871::bigint)  /* South Beach */,
             (9751::bigint)  /* South Beach */,
             (17564872::bigint)  /* South Jetty (South Beach) */,
             (12651087::bigint)  /* South Jetty Beach 3 Day Use */,
             (2867841::bigint)  /* South Jetty Eastside */,
             (9714::bigint)  /* South Jetty Siuslaw River Beach Access 1 */,
             (18681201::bigint)  /* South Jettybeach */,
             (9773::bigint)  /* Sporthaven Beach */,
             (9265450::bigint)  /* Spouting Horn */,
             (9781::bigint)  /* Stonefield Beach */,
             (13031052::bigint)  /* Strawberry Hill Wayside */,
             (3661839::bigint)  /* Sunset Bay Beach */,
             (13638705::bigint)  /* Sunset Beach */,
             (17251238::bigint)  /* Sunset Beach State Recreation Site */,
             (2555786::bigint)  /* Sw 34Th St. Beach Access */,
             (9783::bigint)  /* Swim Beach */,
             (13952025::bigint)  /* Taft Bay */,
             (8121027::bigint)  /* Taft Beach */,
             (9715::bigint)  /* Tolovana Beach SRS */,
             (9774::bigint)  /* Trestle Beach */,
             (1764302::bigint)  /* Tunnel Beach */,
             (9754::bigint)  /* Turner Lake Beach Area */,
             (9739::bigint)  /* Wakeman Beach */,
             (13704506::bigint)  /* Walton Beach */,
             (14173849::bigint)  /* Warehouse Beach */,
             (9736::bigint)  /* Westport Beach */,
             (9756::bigint)  /* Whaleshead Beach */,
             (9731::bigint)  /* Whisky Run Beach */,
             (11535337::bigint)  /* Willow Bar Beach */,
             (7832717::bigint)  /* Wilson Beach */,
             (9501133::bigint)  /* Winchuck State Recreation Site */,
             (519513::bigint)  /* Yachats Ocean Road State Wayside */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://oregon.public.law/rules/oar_736-021-0070'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
