-- State-agency rule codify: Oregon Islands National Wildlife Refuge — Dog Walking Activity Page (USFWS Public Use Policy)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Fish and Wildlife Service (id=308)
-- Subtype: agency_administrative_policy
-- Rule:    on_leash  (section=sand)
-- States:  OR
-- PAD-US filter: mng_type=FED mng_name=FWS unit_name~'%oregon islands%'
-- Affected beaches: 13
--
--   fid 9777  Baker Beach
--   fid 14154320  Coquille Point
--   fid 17326257  D River Beach Wayside
--   fid 8314398  D River State Recreation Area
--   fid 9741  Merchants Beach
--   fid 9786  Moolack Beach
--   fid 9763  Neskowin Beach
--   fid 1439671  Ocean Beach
--   fid 9790  Short Sand Beach
--   fid 9773  Sporthaven Beach
--   fid 9715  Tolovana Beach SRS
--   fid 1764302  Tunnel Beach
--   fid 9739  Wakeman Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'agency_administrative_policy',
       'Oregon Islands National Wildlife Refuge — Dog Walking Activity Page (USFWS Public Use Policy)',
       308,
       ARRAY['dog_policy']::text[],
       'https://www.fws.gov/refuge/oregon-islands/visit-us/activities/dog-walking',
       'USFWS Oregon Islands National Wildlife Refuge — Dog Walking Activity Page (Public Use Policy)

OPERATIVE RULE: Dogs are permitted ONLY at Coquille Point in Bandon, OR (the single mainland section of the refuge open to public use). For the protection of pets, wildlife, and visitors, all pets are required to be on leash.

Context:
- Oregon Islands NWR comprises ~1,854 offshore rocks and islands along the OR coast
- All coastal rocks and islands remain closed to public access at all times to protect seabirds, marine mammals (Harbor Seals, pinnipeds)
- Coquille Point is the only mainland-accessible refuge unit:
  - Short walkway with benches, interpretive signs, picnic area
  - Parking access via wooden stairways at the western end of 11th and 8th streets in Bandon
- Pets must remain leashed; migratory birds protected under Migratory Bird Treaty Act
- Beaches PAD-US-tagged FED/FWS within or adjacent to the refuge are mostly OFFSHORE rocks/islands where humans (and dogs) can''t legally land — so the on_leash rule applies effectively only to Coquille Point shoreline access
- Per-beach status_note should clarify "Coquille Point only — other PAD-US-tagged refuge units (offshore rocks) are closed to public access; the on_leash rule is irrelevant at those because humans cannot land with dogs"

Citation: Oregon Islands National Wildlife Refuge — Dog Walking page (USFWS)
URL: https://www.fws.gov/refuge/oregon-islands/visit-us/activities/dog-walking
Verbatim: "Dogs are permitted only at Coquille Point. For the protection of pets, wildlife and visitors, all pets are required to be on leash."

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'auto_encapsulated_2026_05_18_phase4', 'coquille_point_only', 'true', 'offshore_rocks_closed_to_landing', 'true')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.fws.gov/refuge/oregon-islands/visit-us/activities/dog-walking'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'USFWS Oregon Islands NWR: ''Dogs are permitted only at Coquille Point. For the protection of pets, wildlife and visitors, all pets are required to be on leash.'' Most refuge units are offshore rocks closed to all public access.',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9777::bigint)  /* Baker Beach */,
             (14154320::bigint)  /* Coquille Point */,
             (17326257::bigint)  /* D River Beach Wayside */,
             (8314398::bigint)  /* D River State Recreation Area */,
             (9741::bigint)  /* Merchants Beach */,
             (9786::bigint)  /* Moolack Beach */,
             (9763::bigint)  /* Neskowin Beach */,
             (1439671::bigint)  /* Ocean Beach */,
             (9790::bigint)  /* Short Sand Beach */,
             (9773::bigint)  /* Sporthaven Beach */,
             (9715::bigint)  /* Tolovana Beach SRS */,
             (1764302::bigint)  /* Tunnel Beach */,
             (9739::bigint)  /* Wakeman Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.fws.gov/refuge/oregon-islands/visit-us/activities/dog-walking'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
