-- 20260507_beach_descriptions.sql
--
-- Cache table for LLM-generated beach descriptions. One row per beach.
-- Description is generated by Sonnet from a curated input bundle:
--   - zones[] (sections + rules + time windows + seasons)
--   - cpad_parent_unit (when linked)
--   - verified_physical_features (OSM cliff/pier/stream/etc. inside or
--     within 200m of centroid)
--
-- Voice: warm, second-person imperative, activity-led. Single paragraph.
-- Cost: ~$0.003 per beach via Sonnet 4.5.
--
-- Source values:
--   'sonnet'  - LLM-generated (default)
--   'manual'  - hand-edited via admin UI (protected from regeneration)
--   'wikipedia' - sourced from Wikipedia article extract (overlay)

begin;

create table if not exists public.beach_descriptions (
  arena_group_id  bigint primary key references public.beaches_gold(fid) on delete cascade,
  description     text   not null,
  source          text   not null default 'sonnet'
                  check (source in ('sonnet','manual','wikipedia')),
  model           text,                              -- e.g., 'claude-sonnet-4-5-20250929'
  input_hash      text,                              -- sha256 of input bundle for cache invalidation
  generated_at    timestamptz default now(),
  updated_at      timestamptz default now()
);

create index if not exists beach_descriptions_source_idx
  on public.beach_descriptions(source);

-- RLS: anon can read (descriptions are public); writes via service role only
alter table public.beach_descriptions enable row level security;
create policy beach_descriptions_anon_read on public.beach_descriptions
  for select to anon, authenticated using (true);

-- Extend get_beach_info to return description
create or replace function public.get_beach_info(p_fid bigint)
returns jsonb
language sql
stable
security definer
set search_path to 'public'
as $$
  select jsonb_build_object(
    'beach', jsonb_build_object(
      'fid',           g.fid,
      'location_id',   g.location_id,
      'name',          g.name,
      'display_name',  coalesce(g.display_name_override, g.name),
      'county',        g.county_name,
      'state',         g.state,
      'address',       g.address,
      'website',       g.website,
      'timezone',      g.timezone,
      'lat',           st_y(g.geom),
      'lng',           st_x(g.geom),
      'geom',          st_asgeojson(g.geom)::jsonb,
      'open_time',     g.open_time,
      'close_time',    g.close_time,
      'is_scoreable',  g.is_scoreable
    ),
    'dog_policy', case when bdp.arena_group_id is not null then
      jsonb_build_object(
        'dogs_allowed',           bdp.dogs_allowed,
        'leash_policy',           bdp.leash_policy,
        'has_on_leash',           bdp.has_on_leash,
        'has_off_leash',          bdp.has_off_leash,
        'off_leash_flag',         bdp.off_leash_flag,
        'zone_rules',             bdp.zone_rules,
        'consensus_confidence',   bdp.consensus_confidence,
        'disagreement_flag',      bdp.disagreement_flag
      ) else null end,
    'amenities', case when ba.arena_group_id is not null then
      jsonb_build_object(
        'has_parking',         ba.has_parking,
        'parking_type',        ba.parking_type,
        'parking_notes',       ba.parking_notes,
        'has_restrooms',       ba.has_restrooms,
        'has_showers',         ba.has_showers,
        'has_picnic_area',     ba.has_picnic_area,
        'has_drinking_water',  ba.has_drinking_water,
        'has_food',            ba.has_food,
        'has_fire_pits',       ba.has_fire_pits,
        'has_lifeguards',      ba.has_lifeguards,
        'has_disabled_access', ba.has_disabled_access,
        'hours_text',          ba.hours_text
      ) else null end,
    'description', case when bd.arena_group_id is not null then
      jsonb_build_object(
        'text',         bd.description,
        'source',       bd.source,
        'generated_at', bd.generated_at
      ) else null end
  )
  from public.beaches_gold g
  left join public.beach_dog_policy bdp on bdp.arena_group_id = g.group_id
  left join public.beach_amenities  ba  on ba.arena_group_id  = g.group_id
  left join public.beach_descriptions bd on bd.arena_group_id = g.fid
  where g.fid = p_fid and g.is_active
  limit 1;
$$;

grant execute on function public.get_beach_info(bigint)
  to anon, authenticated, service_role;

commit;
