-- md_state_park_baseline_v2.sql
--
-- MARYLAND STATE-PARK SYSTEM CODIFY
-- Generated by scripts/gen_state_park_baseline.py on 2026-05-22.
--
-- ─── Critical framing ───────────────────────────────────────────────
--
-- Maryland has NO statewide leash law.
-- COMAR 08.07.06.17 (Pets) — Maryland Park Service, Use of State Parks governs ONLY beaches inside the Maryland
-- state-park system. Beyond state parks, leash rules are creatures of local ordinances (counties + cities) which vary widely.
--
-- THREE parts:
--   1. policy_source row for COMAR 08.07.06.17 (Pets)
--   2. BPS rows attaching the ps to 9 state-park beach(es): [6310347, 18144392, 19499672, 12995222, 20146661, 2631955, 5773745, 10346736, 18941056]
--   3. state_dogs_policy seed (no-statewide-law framing)
--
-- Per [[page-level-over-agency-level]]: source_url is the deep-link, not the agency homepage.
-- Per [[state-dogs-policy-honest-framing]]: state_dogs_policy seed reflects
-- absence of statewide law.

begin;

-- ─── 1. Ensure agency row (canonical bare name) ────────────────────

INSERT INTO public.agency (name, type, short_name, web_url)
SELECT 'Maryland Department of Natural Resources',
       'state_department'::agency_type,
       'MD DNR',
       'https://dnr.maryland.gov/'
WHERE NOT EXISTS (
  SELECT 1 FROM public.agency
   WHERE name = 'Maryland Department of Natural Resources'
     AND type = 'state_department'::agency_type
);

-- ─── 2. Insert policy_source row for the state-park rule ───────────

INSERT INTO public.policy_source
  (subtype, citation, issuing_agency_id, scope, source_url, full_text, effective_date)
SELECT
  'state_regulation',
  'COMAR 08.07.06.17 (Pets) — Maryland Park Service, Use of State Parks',
  (SELECT id FROM public.agency
    WHERE name = 'Maryland Department of Natural Resources'
      AND type = 'state_department'::agency_type),
  ARRAY['dog_policy']::text[],
  'https://regs.maryland.gov/us/md/exec/comar/08.07.06.17',
  $body$COMAR 08.07.06.17 Pets. A. Developed Areas. (1) Except for guide service dogs, pets of any kind are not allowed on a picnic area, cabin area, camping area, or other restricted area of a State park. (2) The Service reserves the right to designate pet areas in a State park. In these areas pets shall be on a leash with a maximum length of 6 feet. B. Undeveloped Areas. Pets are permitted on a leash with a maximum length of 10 feet. [Title 08 DNR, Subtitle 07 Forests and Parks, Chapter 08.07.06 Use of State Parks. Adopted effective October 11, 1993 (20:20 Md. R. 1568).] NOT a statewide leash law — applies only to lands inside the MD state-park system.$body$,
  DATE '1993-10-11'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policy_source
   WHERE citation LIKE 'COMAR 08.07.06.17 (Pets)%'
);

-- ─── 3. BPS rows: attach ps to state-park beaches ──────────────────
--
-- Beach fids passed via --fids. Each beach inside the state-park
-- system gets one BPS row attaching the COMAR/OAR/WAC/equivalent
-- citation. Section = 'sand'; rule = 'on_leash'.

INSERT INTO public.beach_policy_source
  (beach_fid, policy_source_id, section, rule, operative_status,
   evidence_verbatim, evidence_url, status_note, region_name)
SELECT v.fid, ps.id, 'sand', 'on_leash', 'operative'::operative_status,
       $body$COMAR 08.07.06.17 (Pets) — Maryland Park Service, Use of State Parks: see policy_source.full_text for verbatim quote.$body$,
       ps.source_url,
       NULL,
       NULL
FROM (VALUES
  (6310347::bigint),
  (18144392::bigint),
  (19499672::bigint),
  (12995222::bigint),
  (20146661::bigint),
  (2631955::bigint),
  (5773745::bigint),
  (10346736::bigint),
  (18941056::bigint)
) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.citation LIKE 'COMAR 08.07.06.17 (Pets)%'
ON CONFLICT (beach_fid, policy_source_id, section, (COALESCE(region_name, '__default__'::text)), rule) DO NOTHING;

-- ─── 4. state_dogs_policy seed (honest no-statewide-law framing) ─
--
-- DELETE+INSERT pattern (the prod table has no PRIMARY KEY on state_code;
-- ON CONFLICT (state_code) DO UPDATE fails plan-time on prod — see
-- [[state-dogs-policy-honest-framing]] + task #150).

DELETE FROM public.state_dogs_policy WHERE state_code = 'MD';

INSERT INTO public.state_dogs_policy
  (state_code, state_name, dogs_allowed, default_rule,
   has_on_leash, has_off_leash,
   source_quote, source_url, ordinance_ref,
   scope_notes, confidence, scraped_at)
VALUES
  ('MD', 'Maryland', 'mixed', 'mixed',
   false, false,
   'Maryland has no statewide leash law. State-park system governed by COMAR 08.07.06.17 (6-ft developed / 10-ft undeveloped, no off-leash) — but that rule binds only inside state-park boundaries. Beyond state parks, leash rules are entirely creatures of local ordinances (counties + cities) which vary widely. Many private community / HOA waterfronts have only operator-posted rules. Public access on tidal beaches is recognized by common law (Maryland Public Trust Doctrine) but not via a statewide statute analogous to Oregon''s Beach Bill.',
   'https://dnr.maryland.gov/publiclands/pages/pets.aspx',
   '(no statewide leash law; state-park rule at COMAR 08.07.06.17)',
   'Last-resort fallback only. Beaches inside state-park polygons get the COMAR 08.07.06.17 (Pets) rule via explicit BPS rows. Municipal/county beaches via local codify. Federal-land beaches via federal codify. This row fires only for beaches not covered by any per-jurisdiction codify.',
   0.3,
   now());

commit;

-- ─── Notes / follow-ups ────────────────────────────────────────────
--
-- 1. Other Maryland state-park beaches not in --fids will not
--    automatically attach to this ps. Extend Part 3 with more fids as
--    they surface in ingestion.
-- 2. If a state-park beach has a seasonal carve-out (e.g., Memorial-Day-
--    through-Labor-Day prohibition), run extract_temporal_from_policy_source.py
--    on this ps_id post-apply to lift the window into beach_policy_source_temporal.
-- 3. Apply with:
--      supabase db query --linked -f supabase/migrations/md_state_park_baseline_v2.sql
