-- State-agency rule codify: Siuslaw National Forest Pet Policy - 36 CFR §261.16(j) + snowy plover seasonal closure Mar 15-Sep 15
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Forest Service (id=292)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  OR
-- PAD-US filter: mng_type=FED mng_name=USFS unit_name~'%siuslaw national forest%'
-- Affected beaches: 6
--
--   fid 9777  Baker Beach
--   fid 1439671  Ocean Beach
--   fid 13230871  South Beach
--   fid 12651087  South Jetty Beach 3 Day Use
--   fid 9714  South Jetty Siuslaw River Beach Access 1
--   fid 9265450  Spouting Horn
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'Siuslaw National Forest Pet Policy - 36 CFR §261.16(j) + snowy plover seasonal closure Mar 15-Sep 15',
       292,
       ARRAY['dog_policy']::text[],
       'https://www.fs.usda.gov/r06/siuslaw/about-area/faqs',
       'Siuslaw National Forest — Pet Policy

OPERATIVE RULE (36 CFR §261.16(j) + Siuslaw NF admin policy):
- Developed sites (campgrounds, picnic areas): Dogs MUST be on a leash no more than 6 feet long, or otherwise under physical restrictive control
- Dogs must wear a collar with current tags at all times
- Owners must pack out dog waste
- The forest recommends keeping dogs leashed while hiking for safety

SEASONAL BEACH CLOSURE (March 15 – September 15):
- Some beach areas are CLOSED to dogs March 15 – September 15 to protect nesting Western Snowy Plovers (threatened species)
- These restricted areas are posted on-site and mapped by USFS
- Outside seasonal closure zones, the standard 6-foot leash requirement applies on developed beach recreation sites (South Jetty Beach, Ocean Beach Day Use, Tillicum Beach Campground, etc.)

Citation: Siuslaw National Forest FAQs + 36 CFR §261.16(j) — Pet Policy
URL: https://www.fs.usda.gov/r06/siuslaw/about-area/faqs
Verbatim: "In developed sites such as campgrounds and picnic areas, dogs must always be restrained or on a leash no more than 6 feet long. Some beach areas are closed to dogs March 15 – September 15 to protect nesting Western Snowy Plovers."
Subtype: federal_regulation (36 CFR §261.16(j) baseline + forest-specific snowy plover seasonal closure)

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'agent_dispatch_2026_05_18_afk')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.fs.usda.gov/r06/siuslaw/about-area/faqs'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       '6-ft leash + snowy plover Mar 15-Sep 15 closure',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9777::bigint)  /* Baker Beach */,
             (1439671::bigint)  /* Ocean Beach */,
             (13230871::bigint)  /* South Beach */,
             (12651087::bigint)  /* South Jetty Beach 3 Day Use */,
             (9714::bigint)  /* South Jetty Siuslaw River Beach Access 1 */,
             (9265450::bigint)  /* Spouting Horn */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.fs.usda.gov/r06/siuslaw/about-area/faqs'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
