-- State-agency rule codify: Oregon Dunes National Recreation Area Pet Policy - 36 CFR §261.16(j) + snowy plover seasonal closure
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: United States Forest Service (id=292)
-- Subtype: federal_regulation
-- Rule:    on_leash  (section=sand)
-- States:  OR
-- PAD-US filter: mng_type=FED mng_name=USFS unit_name~'%oregon dunes%'
-- Affected beaches: 3
--
--   fid 13230871  South Beach
--   fid 12651087  South Jetty Beach 3 Day Use
--   fid 9714  South Jetty Siuslaw River Beach Access 1
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'federal_regulation',
       'Oregon Dunes National Recreation Area Pet Policy - 36 CFR §261.16(j) + snowy plover seasonal closure',
       292,
       ARRAY['dog_policy']::text[],
       'https://www.fs.usda.gov/r06/siuslaw/recreation/rules-and-guidelines',
       'Oregon Dunes National Recreation Area (USFS, within Siuslaw NF) — Pet Policy

OPERATIVE RULE (36 CFR §261.16(j) + Oregon Dunes NRA-specific):
- Within developed recreation sites: Dogs MUST be on a leash no longer than 6 feet, or otherwise under physical restrictive control
- Developed sites include campgrounds, day-use areas, picnic areas, parking areas, and trailheads
- Dogs must wear a collar with current tags at all times
- Visitors must pick up after their dogs

SEASONAL BEACH CLOSURE (March 15 – September 15):
- Designated beach closure areas PROHIBIT DOGS ENTIRELY (even leashed) during snowy plover nesting season
- Posted on-site and mapped by USFS
- Outside closure zones during other seasons: on_leash applies
- Status: rule=on_leash by default; sub-zone not_allowed during plover season per beach posting

Citation: Oregon Dunes NRA Pet Policy + 36 CFR §261.16(j)
URL: https://www.fs.usda.gov/r06/siuslaw/recreation/rules-and-guidelines
Verbatim: "Within developed recreation sites, dogs must be on a leash no longer than 6 feet, or otherwise under physical restrictive control. Designated beach closure areas prohibit dogs entirely (even leashed dogs) to protect the threatened western snowy plover during breeding season (March 15 – September 15)."
Subtype: federal_regulation

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       jsonb_build_object('codify_source_curator', 'agent_dispatch_2026_05_18_afk')
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.fs.usda.gov/r06/siuslaw/recreation/rules-and-guidelines'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       '6-ft leash + snowy plover seasonal closure',
       ps.source_url, NOW(), NOW()
FROM (VALUES (13230871::bigint)  /* South Beach */,
             (12651087::bigint)  /* South Jetty Beach 3 Day Use */,
             (9714::bigint)  /* South Jetty Siuslaw River Beach Access 1 */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.fs.usda.gov/r06/siuslaw/recreation/rules-and-guidelines'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
