-- State-agency rule codify: Lewis and Clark National Historical Park Pet Policy (NPS — 6-ft leash on all park areas; Middle Village Station Camp excepted)
-- Generated by scripts/derive_policy_source_for_jurisdiction.py --state-agency-rule 2026-05-18
--
-- Agency: National Park Service (id=307)
-- Subtype: agency_administrative_policy
-- Rule:    on_leash  (section=sand)
-- States:  WA
-- PAD-US filter: mng_type=FED mng_name=NPS unit_name~'%lewis%clark%'
-- Affected beaches: 1
--
--   fid 9849  Waikiki Beach
--
-- Per playbook tenet #5: bps INSERT auto-fires trigger cascade.
-- NO manual two-pass refire needed (data-only migration, not function-body change).
BEGIN;

-- 1. policy_source insert (idempotent via source_url uniqueness check)
INSERT INTO public.policy_source (
    subtype, citation, issuing_agency_id, scope, source_url, full_text,
    effective_date, last_verified, metadata
)
SELECT 'agency_administrative_policy',
       'Lewis and Clark National Historical Park Pet Policy (NPS — 6-ft leash on all park areas; Middle Village Station Camp excepted)',
       307,
       ARRAY['dog_policy']::text[],
       'https://www.nps.gov/lewi/planyourvisit/pets.htm',
       'Lewis and Clark National Historical Park — Pet Policy

OPERATIVE RULE: Pets must be leashed at all times with a leash no more than 6 feet (1.8 meters) in length. Owners must maintain control and cannot leave pets unattended or tied up. Pets are prohibited from all indoor public buildings and visitor center areas (except service dogs and NPS volunteer dogs). Owners must pick up after their pets using plastic bags and dispose waste in designated trash receptacles.

Citation: Lewis and Clark National Historical Park Pet Policy (NPS official page)
URL: https://www.nps.gov/lewi/planyourvisit/pets.htm
Verbatim: "Pets must be leashed at all times with a leash no more than 6 feet (1.8 meters) in length."

Subtype: agency_administrative_policy (implements 36 CFR §2.15 baseline; adds explicit 6-ft leash spec).

KEY EXCEPTION (NOT applied to this beach):
- Middle Village Station Camp unit — dogs completely prohibited (cultural significance to local tribes). The 1 PAD-US-tagged beach in WA in this codify ship is NOT Middle Village Station Camp; default on_leash applies.

[Codified via codify v1 --state-agency-rule 2026-05-18.]',
       NULL::date,
       NOW(),
       NULL
WHERE NOT EXISTS (
    SELECT 1 FROM public.policy_source
    WHERE source_url = 'https://www.nps.gov/lewi/planyourvisit/pets.htm'
);

-- 2. beach_policy_source links (idempotent via ON CONFLICT)
INSERT INTO public.beach_policy_source (
    beach_fid, policy_source_id, section, rule, operative_status,
    evidence_verbatim, evidence_url, extracted_at, last_verified
)
SELECT v.fid, ps.id, 'sand', 'on_leash',
       'operative'::operative_status,
       'Lewis & Clark NHP: ''Pets must be leashed at all times with a leash no more than 6 feet (1.8 meters) in length.''',
       ps.source_url, NOW(), NOW()
FROM (VALUES (9849::bigint)  /* Waikiki Beach */) AS v(fid)
CROSS JOIN public.policy_source ps
WHERE ps.source_url = 'https://www.nps.gov/lewi/planyourvisit/pets.htm'
ON CONFLICT (beach_fid, policy_source_id, section) DO NOTHING;

COMMIT;
